# Generated by Django 5.2.11 on 2026-02-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='analyze_sentiment',
            field=models.BooleanField(default=True),
        ),
    ]
