# Generated by Django 5.2.11 on 2026-02-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_respondent_answer_respondent'),
        ('results', '0006_rename_question_to_interview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Interview',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='interview',
        ),
    ]
