# Generated by Django 5.2.11 on 2026-02-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_rename_question_to_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='uuid',
        ),
    ]
