# Generated by Django 5.2.11 on 2026-02-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_interview_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
