# Generated by Django 5.2.11 on 2026-02-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0014_add_respondent_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='is_complete',
        ),
    ]
